### PR TITLE
Updates from upstream

### PR DESCRIPTION
**Pull request by exprez135**
Cherry-picks:

- 471c2a3d59b89509aec3505f6f169081f17dd4ee
- 1057996f237d9dec455ae2c48729ad9f536ddb12
- 4497f6f128739ccc6413ae5ca523b09df505f63c
- 068b4c7d51ae81c1087f2828e493c026a1851e8b
- b006cbaa9afc31ddb70c24189ee7b6dc9d073c81
- 0ec72d94b0792b05495b98b907a6f5177c8034ca
- 1be6f4db485157080da57273ead1993ab5f59208

Summary of changes:
- Translation updates for Russian and Chinese
- Updates from releases 1.7.3 & 1.7.4
- Updates to packages (i.e. minimist)
- Changes for macOS notarization and hardened run-time

### CODE REVIEW

**Comment by notpushkin** [comment]
Hey, thank you so much for this and your other contributions and sorry I'm taking so long to respond! I've been busy with some other projects and my dayjob lately. I'll do some more thorough review of this one as I believe some of the commits might conflict with the changes in this repo but #29 #30 both LGTM and I'll merge them later tonight for sure (I swear! :D)

**Comment by exprez135** [comment]
No problem at all! Let me know if I can do anything to help. By now there is probably plenty more to bring in from upstream too. If you want me to update this pull request before you take a look, I'm fully willing. Thanks!

**Comment by yashha** [comment]
lgtm tbh, should not break anything; very nice project :)

**Comment by aquelehugo** [comment]
Why is this stuck?

**Comment by marshall-mcmullen** [comment]
Any update on this? LOVE this project but would like to see an update... Thanks!!

**Comment by aquelehugo** [comment]
@marshallmcmullen the owner abandoned this repo absolutely, no commit or comment since May. One man open-source projects problems :man_shrugging:

**Comment by notpushkin** [comment]
😢

**Comment by yashha** [comment]
@notpushkin 
Could you add a collaborator or should somebody fork it?
There are people that would help.

**Comment by notpushkin** [comment]
@yassha That'd probably be a nice idea since it's been half a year and I still can't find some capacity to work on this project. I have to focus on my day job and mental health so major side-projects like this is a no-go for me apparently.

@exprez135 Any chance you would be interested in _maintaining_ this project? I'll try to provide as much guidance as I can.

**Comment by aquelehugo** [comment]
@notpushkin I think everybody is busy :laughing:
I can't take full responsibility, but I may be part of the maintainers team, as long as we let the position open for more people to join

**Comment by lamixer** [comment]
Hello. Thanks @notpushkin for creating this fork. I got fed up with problems in Geary and switched to Mailspring-Libre about a month ago. I would love to see it updated more regularly as well. I'm not a coder at all so I'm not sure how I could help, though I do have some time available (sometimes)! 

Mailspring seems to have had a lull in updates (no releases since the end of May) so this might be a good time to 'sync up' and develop a plan to make the Libre branch as easy to maintain as possible.

**Comment by exprez135** [comment]
Hello all! So sorry @notpushkin for never replying; I've changed up my email in the past few months and I never got updates from this thread. I definitely do not wish this project to die, even as I've moved to using mutt or aerc for almost all my email.

I'm hoping to look into updating from upstream whenever I have the chance. I played around with it for a few hours this morning and I'll continue later. If I can get everything synced up and working then I will gladly help to maintain the project. Look for an update soon :)

**Comment by exprez135** [comment]
New pull request with major rebase: #42 
I would appreciate anyone who can test out the builds!

**Pull request closed without merging**
