### PR TITLE
ci: Bring back Travis

### PR DESCRIPTION
**Pull request by notpushkin**

### CODE REVIEW

**Comment by notpushkin** [comment]
From what I see Linux build works and macOS will need to be further adjusted to work without code signing, and we need to upload artifacts somewhere (GitHub releases for tags, what about other commits?)

**Comment by notpushkin** [comment]
Added experimental artifact upload to Netlify, hope it works (previous build took horrific 17 min 54 sec)

**Comment by alexanderadam** [comment]
Awesome, you are great! :+1:

**Comment by notpushkin** [comment]
@alexanderadam It now uploads artifacts (Linux only for now) to transfer.sh, but the logs get obscured so I only see the `.rpm` URL (see [this build](https://travis-ci.com/notpushkin/Mailspring-Libre/builds/146665949)). Wanna pick it up from here?

**Comment by alexanderadam** [comment]
I will try when I have time but I won't be able to promise anything.

**Comment by notpushkin** [comment]
I couldn't ask for more. Thank you so much for your help!

**Comment by alexanderadam** [comment]
You are awesome! :pray:

**Pull request merged**
