### PR TITLE
Clean .travis.yml and add MacOS (.dmg) builds

### PR DESCRIPTION
**Pull request by exprez135**
1. Adds MacOS/OSX builds back to Travis CI,
2. Removes matrix alias: "matrix" -> "jobs",
3. Updates to use "cleanup: false" instead of "skip_cleanup: true",
4. Removes deprecated use of "sudo".

### CODE REVIEW

**Comment by notpushkin** [comment]
So it... just worked after just enabling the `osx` job back? I can hardly believe my eyes!

```
  electron-osx-sign electron-osx-sign@0.4.14 +0ms
  electron-osx-sign Finding `Developer ID Application` certificate for distribution outside the Mac App Store... +3ms
  electron-osx-sign Executing... security find-identity -v +1ms
WARNING: Code sign failed; please retry manually. Error: No identity found for signing.
WARNING: The appleId sub-property is required when using notarization, notarize will not run
WARNING: The appleIdPassword sub-property is required when using notarization, notarize will not run
```

Does it work alright without a signature (maybe with the usual “Open Anyway” dance like with other unsigned apps)? Perhaps we should disable this step altogether?

**Comment by exprez135** [comment]
It did indeed! Without code signing, when opening the actual .app, you have to right click and pick "Open". I'm not super familiar with how to get the code signing to work if we did want that.
For now, at least, I would say we can just specify that in the installation instructions.

**Comment by notpushkin** [comment]
Apparently `skip_cleanup` was the right way after all: https://travis-ci.com/github/notpushkin/Mailspring-Libre/jobs/311444586#L2458
Apart from that it builds flawlessly and seems to work alright on my girlfriend's mac, thank you once again!

**Comment by specter78** [comment]
For signing and notarisation, https://github.com/mitchellh/gon can be tried

**Comment by notpushkin** [comment]
@specter78 For me it's sad to see macOS becoming a more closed ecosystem with Apple telling users what apps they can and cannot run (even [shell scripts][1] are being checked now!).

[1]: https://sigpipe.macromates.com/2020/macos-catalina-slow-by-design/

I'm not 100% opposed to supporting app signing, but I'm not personally interested either. For now I'd rather just tell users how they can override this (which isn't that bad IIRC, you just do a couple clicks once). If it becomes too obnoxious, perhaps we could crowdfund a certificate.

**Pull request merged**
