### PR TITLE
Sync up to v1.7.8

### LINKED ISSUE #33: Upstream update?
Hello,

Any chance to get an upstream update?

Upstream mailspring solved important issues, like yahoo authentication not working anymore.

Thanks for your work. Love the idea of your fork.

### LINKED ISSUE #39: Remove nag screen when adding more than four accounts
When adding more than four accounts, this message appears:

You're syncing more than four accounts — please consider paying for Mailspring Pro! Manage | Dismiss

So I guess this screen and the check for it can be removed?

### PR DESCRIPTION
**Pull request by exprez135**
Hello folks! This is a sort "refresh" on the Mailspring Libre build, taking the upstream and re-applying patches from scratch. **Please feel free to help test this.** You can download built packages from Travis: https://travis-ci.com/github/exprez135/Mailspring-Libre. If you notice any regressions, problems, or bugs let me know!

This PR is not meant to merge nicely, but to take the place of the current state. Some changes since the fork have probably been reversed (e.g. onboarding hasn't been changed), but I haven't experienced any issues in my testing thus far.

If everything works nicely, we can re-position ourselves from here to focus on fixing other issues and accomplishing greater goals.

Overall:
- Updates to upstream v1.7.8
- Fixes #39
- Fixes #33 

---
Build links:
- macOS: https://files.catbox.moe/zo7wm0.dmg
- Windows: https://files.catbox.moe/2kww8d.msi
- Linux (deb): https://files.catbox.moe/a47adw.deb
- Linux (rpm): https://files.catbox.moe/z1htf3.rpm

### CODE REVIEW

**Comment by exprez135** [comment]
### To-do before implementing

- [x] OAuth for Mailspring Libre (or revert to options for app password)
- [ ] Test builds on all three platforms (let me know if you have tested)

---

Updates:
- Created website: https://mailspringlibre.org
- I disabled OAuth in favor of plain login (recommending app passwords, which also work for G Suite/Google Workspace accounts)

**Comment by notpushkin** [comment]
Thank you so much, incredible work over here! I went through the commits and things look pretty good so far. Going to give it a go now; still need volunteers to try it on Windows / macOS.

I've invited you as a collaborator on this repo, so you should be able to push your changes over here if things work out well!

**Comment by exprez135** [comment]
macOS on my end seems to be alright. I tested on Windows but it looks like #36 is still happening.

If there are no objections, I can go ahead and push this so we can put out a release for the platforms that work. If we can get Windows working then we'll update then.

**Comment by aquelehugo** [comment]
Man, that update was really missing... Performance improved and bugs went away. Thank you so much @exprez135 :heart:

**Pull request merged**
