### PR TITLE
chores: disable signing for now

### PR DESCRIPTION
**Pull request by alexanderadam**
The missing keys [lead to travis failing](https://travis-ci.com/notpushkin/Mailspring-Libre/jobs/281436496#L775). Either you add a proper key (you [already added an issue for that](https://github.com/notpushkin/Mailspring-Libre/issues/2)) or the behaviour should be changed.

### CODE REVIEW

**Comment by notpushkin** [comment]
Travis didn't seem to pick this up though :D Let's try to [push it through](https://stackoverflow.com/questions/17606874/ddg#17624403).

**Comment by notpushkin** [comment]
Alright, it complains about the config: `Could not parse notpushkin/Mailspring-Libre:.travis.yml@bb9d2bfa5c95e862` (not very helpful!)

**Comment by notpushkin** [comment]
It'll need a few more tweaks I'm afraid: it's currently building MailSync from source (and needs to decrypt an ssh key first) and we'll probably want to just use the prebuilt binaries. → #6

**Comment by alexanderadam** [comment]
Ah okay. I'm rather for using proper keys anyway :wink:

**Pull request closed without merging**
